revert separate uniffi binary and bitwarden action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -220,42 +220,72 @@ jobs:
         ./node-uniffi/build-ios.sh
         ./examples/ios/LuminaDemo/copy_bindings.sh
 
-    # bitwarden's boot-simulator requires gtimeout
-    - name: install brew dependencies
-      run: brew install coreutils
+    - name: create and boot simulator
+      run: |
+        # booting the simulator often hangs
+        # https://github.com/actions/runner-images/issues/12777#issuecomment-3431315347
+        # so we work this around by killing it and retrying
+        # based on
+        # https://github.com/bitwarden/ios/blob/5dc773e7530566702e672b6795bbed0baca51926/.github/workflows/test.yml#L126
 
-    # booting the simulator often hangs, so it needs to be killed and restarted
-    # https://github.com/actions/runner-images/issues/12777#issuecomment-3431315347
-    - name: boot simulator
-      uses: bitwarden/ios/.github/actions/boot-simulator@5dc773e7530566702e672b6795bbed0baca51926
-      id: boot-simulator
-      with:
-        simulator-name: iPhone 16
-        simulator-version: 26.0.1
+        # install 'gtimeout'
+        brew update
+        brew install coreutils
+
+        # Update the shared cache, not sure if it is needed
+        xcrun simctl runtime dyld_shared_cache update --all
+
+        # Run `xcrun simctl list devicetypes` for more
+        DEVTYPE=com.apple.CoreSimulator.SimDeviceType.iPhone-16
+        # Run `xcrun simctl list runtimes` for more
+        RUNTIME=com.apple.CoreSimulator.SimRuntime.iOS-26-0
+
+        # Create simulator and export it for next steps
+        UDID=$(xcrun simctl create CI-iPhone "$DEVTYPE" "$RUNTIME")
+        echo "SIM_UDID=$UDID" >> "$GITHUB_ENV"
+
+        attempt=1
+        while [ $attempt -le 5 ]; do
+          echo "booting simulator (attempt $attempt)"
+
+          # according to bitwarden, successful boot always takes under 2 mins
+          # but from what I saw it usually takes ~45s
+          if gtimeout -s SIGKILL 90s xcrun simctl bootstatus "$UDID" -b; then
+            exit 0
+          else
+            echo "simulator boot timed out"
+            xcrun simctl shutdown "$UDID" || true # prevents "Unable to shutdown device in current state: Shutdown" error
+            attempt=$((attempt + 1))
+            sleep 2
+          fi
+        done
+
+        echo "all boot attempts failed"
+        exit 1
 
     - name: xcode clean build
       working-directory: examples/ios/LuminaDemo
       env:
         NSUnbufferedIO: "YES"
-        SIMULATOR_ID: ${{ steps.boot-simulator.outputs.simulator-id }}
       run: |
         xcrun xcodebuild build-for-testing \
-          CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
           -scheme LuminaDemo \
-          -destination "id=$SIMULATOR_ID" \
+          -destination "id=${SIM_UDID}" \
+          CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
           -quiet
 
     - name: xcode sim test
       working-directory: examples/ios/LuminaDemo
       env:
         NSUnbufferedIO: "YES"
-        SIMULATOR_ID: ${{ steps.boot-simulator.outputs.simulator-id }}
       run: |
+        # `-parallel-testing-enabled NO` avoids creating clones of the simulator
         xcrun xcodebuild test-without-building \
           -scheme LuminaDemo \
           -sdk iphonesimulator \
-          -destination "id=$SIMULATOR_ID" \
+          -destination "id=${SIM_UDID}" \
           -destination-timeout 360 \
+          -parallel-testing-enabled NO \
           -skip-testing LuminaDemoTests/GrpcClientTest \
           -quiet
 
